### ISSUE TITLE
Support for dark mode?

### ISSUE THREAD

**Issue by virtualjoeri** [somared/KustoNPPLanguage#1]
Hi, this plugin works like a charm but in dark mode it's showing all white blocks of text. Is it possible to support dark mode?

![image](https://github.com/somared/KustoNPPLanguage/assets/99259837/ba8d8af5-c85e-4001-b2fb-b456be9fa8e1)

**Comment by somared** [comment]
Thanks for informing. Added light mode & dark mode support in last commit.
